import Foundation

public struct DescriptionView: View {
    let description: String
    
    public init(description: String) {
        self.description = description
    }
    
    public var body: some View {
        self
    }
    
    public func render(platform: Platform) -> String {
        // The description is already in the correct format for each platform
        // because it was generated by our DSL's render methods
        description
    }
} 